name: security

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  gosec:
    name: Run gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run gosec
        id: gosec
        uses: securego/gosec@master
        with:
          args: -fmt sarif -out gosec.sarif ./...
        continue-on-error: true

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gosec.sarif

      - name: Fail if gosec found issues
        if: steps.gosec.outcome == 'failure'
        run: |
          echo "gosec found issues. See SARIF report."
          # exit 1

